"""add message_hash to orders

Revision ID: 05337d3b4ae2
Revises: 8d113a28fa13
Create Date: 2026-07-14 15:27:57.450519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05337d3b4ae2'
down_revision: Union[str, Sequence[str], None] = '8d113a28fa13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(), nullable=False),
    sa.Column('order_reference', sa.String(), nullable=False),
    sa.Column('message_hash', sa.String(), nullable=True),
    sa.Column('items_ordered', sa.JSON(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_number'), 'orders', ['customer_number'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_merchant_id'), 'orders', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_orders_message_hash'), 'orders', ['message_hash'], unique=False)
    op.create_index(op.f('ix_orders_order_reference'), 'orders', ['order_reference'], unique=True)
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('webhook_type', sa.String(), nullable=False),
    sa.Column('source_number', sa.String(), nullable=False),
    sa.Column('destination_number', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('processed_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_sent', sa.Text(), nullable=True),
    sa.Column('response_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_destination_number'), 'webhook_logs', ['destination_number'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_received_at'), 'webhook_logs', ['received_at'], unique=False)
    op.create_index(op.f('ix_webhook_logs_source_number'), 'webhook_logs', ['source_number'], unique=False)
    op.create_table('bargain_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_number', sa.String(), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('negotiation_rounds', sa.Integer(), nullable=True),
    sa.Column('starting_offer', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('counter_offers', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('customer_satisfaction', sa.Integer(), nullable=True),
    sa.Column('conversion_time_seconds', sa.Integer(), nullable=True),
    sa.Column('ai_model_used', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bargain_logs_customer_number'), 'bargain_logs', ['customer_number'], unique=False)
    op.create_index(op.f('ix_bargain_logs_id'), 'bargain_logs', ['id'], unique=False)
    op.create_index(op.f('ix_bargain_logs_merchant_id'), 'bargain_logs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_bargain_logs_session_id'), 'bargain_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_bargain_logs_started_at'), 'bargain_logs', ['started_at'], unique=False)
    op.create_table('product_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_queries', sa.Integer(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_selling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_frequency', sa.Integer(), nullable=True),
    sa.Column('unique_customers', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('stock_turnover_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_margin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_analytics_id'), 'product_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_product_analytics_merchant_id'), 'product_analytics', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_product_analytics_product_id'), 'product_analytics', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_analytics_product_id'), table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_merchant_id'), table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_id'), table_name='product_analytics')
    op.drop_table('product_analytics')
    op.drop_index(op.f('ix_bargain_logs_started_at'), table_name='bargain_logs')
    op.drop_index(op.f('ix_bargain_logs_session_id'), table_name='bargain_logs')
    op.drop_index(op.f('ix_bargain_logs_merchant_id'), table_name='bargain_logs')
    op.drop_index(op.f('ix_bargain_logs_id'), table_name='bargain_logs')
    op.drop_index(op.f('ix_bargain_logs_customer_number'), table_name='bargain_logs')
    op.drop_table('bargain_logs')
    op.drop_index(op.f('ix_webhook_logs_source_number'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_received_at'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_destination_number'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_orders_order_reference'), table_name='orders')
    op.drop_index(op.f('ix_orders_message_hash'), table_name='orders')
    op.drop_index(op.f('ix_orders_merchant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
