"""add paystack fields to merchant and order

Revision ID: 5f324257384b
Revises: 450f74ade685
Create Date: 2026-07-25 07:00:38.640446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f324257384b'
down_revision: Union[str, Sequence[str], None] = '450f74ade685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('paystack_subaccount_code', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('settlement_bank_code', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('settlement_account_number', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('platform_fee_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('merchants', sa.Column('transfer_recipient_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('paystack_reference', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('paystack_account_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('paystack_bank_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('paystack_expires_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('settlement_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('settlement_reference', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_paystack_reference'), 'orders', ['paystack_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_paystack_reference'), table_name='orders')
    op.drop_column('orders', 'settlement_reference')
    op.drop_column('orders', 'settlement_status')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'paystack_expires_at')
    op.drop_column('orders', 'paystack_bank_name')
    op.drop_column('orders', 'paystack_account_number')
    op.drop_column('orders', 'paystack_reference')
    op.drop_column('merchants', 'transfer_recipient_code')
    op.drop_column('merchants', 'platform_fee_percent')
    op.drop_column('merchants', 'settlement_account_number')
    op.drop_column('merchants', 'settlement_bank_code')
    op.drop_column('merchants', 'paystack_subaccount_code')
    # ### end Alembic commands ###
